name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: azure/docker-login@v1
      with:
        login-server: dockerregistrychethan.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t dockerregistrychethan.azurecr.io/demo-docker:${{ github.sha }}
        docker push dockerregistrychethan.azurecr.io/demo-docker:${{ github.sha }}
